### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by thoppe** [dchackandtell/dchackandtell.github.io#12]
@ajschumacher how hard would it be to get the **s** on our https? Didn't you do that recently for one of your own websites?

**Comment by ajschumacher** [comment]
Yeah I did it using cloudflare, following a guide Ali linked. It’s not hard, but we’d have to get access to the hackandtell.org DNS, and I’m not really sure who even called controls that; maybe gwoz or James, from the NYC group?

**Comment by ajschumacher** [comment]
This guide: https://medium.freecodecamp.org/an-illustrated-guide-for-setting-up-your-website-using-github-cloudflare-5a7a11ca9465

**Comment by thoppe** [comment]
We can put it on hold for now, but if you ever come across those guys we should push them to HTTPS!

**Comment by ajschumacher** [comment]
Let's leave it open for a while and I'll send an email...

**Comment by thoppe** [comment]
This is fixed now! Thanks @ajschumacher for reaching out!

**Comment by ajschumacher** [comment]
Looks like thanks is due to Aditya Mukerjee of H&T NYC! Woo!
