### ISSUE TITLE
Missing text for Round 30

### ISSUE THREAD

**Issue by thoppe** [dchackandtell/dchackandtell.github.io#16]
I can't find any notes for Round 30: Didacts and Narpets anywhere. Does anybody have anything we can put down for it? I think I presented:

https://github.com/thoppe/polysemous-emoji

so that might help grep for something.

**Comment by ajschumacher** [comment]
Hmm! I think this was the last one before I moved back to DC... Here's the link to the meetup event, anyway:

https://www.meetup.com/DC-Hack-and-Tell/events/227724648/

I don't see any proper "write-up," but there are two comments on the meetup event:

@thoppe:

> Great presentations! Anti hearing aids, love hacks, choropleths, and multiple twitter frivolities. I give it 👍👍

@ampetr89:

> Hi everyone! Here's a link to the code to make your own map visualization using AWS :D https://github.com/ampetr/aws-leaflet

So we have enough for a skeleton of a write-up, anyway?

**Comment by thoppe** [comment]
Done! At least now we can see who presented. I added whatever they happened to put in on the signup sheet, cleaned up a bit and added links where I could find them.

https://dc.hackandtell.org/2016/03/08/round-30.html

All the historical links are done!
