### ISSUE TITLE
Missing Round 18!

### ISSUE THREAD

**Issue by thoppe** [dchackandtell/dchackandtell.github.io#3]
Since you've left the area the site hasn't been updated to reflect any new meetups. Can we add these? 

Round 17: Codified Phase Transitions (canceled)
http://www.meetup.com/DC-Hack-and-Tell/events/218931900/

Round 18: Ternary Bits
http://www.meetup.com/DC-Hack-and-Tell/events/220231708/

I _think_ I can do it, I poked around the site a bit and it looks like all the posts are in `_posts`. with the content taken from the HackPad. Did you edit this information by hand into markdown or is there a "pretty" way to do it?

**Comment by ajschumacher** [comment]
Ah! Hi! Yes, you could totally add these! It's just Jekyll (the Jekyll integrated into GitHub) so yeah, markdown with front matter is all it takes. I had been hand-editing from the HackPad, but there could be a faster/easier way, especially when the notes are good! More peeps: @shannonturner @lauralorenz @boxcarton @JessicaGarson
